services:
  mongo:
    image: mongo:latest
    container_name: yorkie-mongo
    ports:
      - "27017:27017"

  yorkie:
    image: yorkieteam/yorkie:latest
    container_name: yorkie-server
    depends_on:
      - mongo
    command:
      [
        "server",
        "--rpc-addr", "0.0.0.0:8080"
        "--mongo-connection-uri", "mongodb://mongo:27017",
        "--backend-use-default-project", "true"   # default 프로젝트 자동 사용
      ]
    ports:
      - "8080:8080"
    environment:
      YORKIE_AUTH_ENABLE: "false"       # 인증 OFF
      YORKIE_CORS_ALLOW_ORIGIN: "*"     # (선택) CORS 허용
