# back-spring/yorkie-server/docker-compose.yml
services:
  mongo:
    image: mongo
    container_name: yorkie-mongo
    ports:
      - "27017:27017"

  yorkie:
    image: yorkieteam/yorkie
    container_name: yorkie-server
    # ↓ 여기에 server 하위 명령을 붙여 줍니다
    command: ["server", "--rpc-addr=0.0.0.0:8080"]
    ports:
      - "8081:8080"
    environment:
      - YORKIE_MONGO_CONNECTION_URI=mongodb://mongo:27017
    depends_on:
      - mongo
