version: '3.8'

services:
  backend:
    image: backend
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0kLmnopQrstUvwxyz  # JWT 시크릿 키 추가
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: db
    build: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
